#
# GitHub Action Workflow for building the UEFI debugger extension.
#
# Copyright (c) Microsoft Corporation
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

name: "Build UEFI Debug Extension"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'UefiDbgExt/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'UefiDbgExt/**'
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64, arm64]
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup MsBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: msbuild UefiDbgExt\uefiext.vcxproj -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }}

      - name: Publish Binary
        if: ${{ matrix.configuration == 'Release' && github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: UefiDbgExt-${{ matrix.platform }}-${{ matrix.configuration }}
          path: UefiDbgExt\${{ matrix.platform }}\${{ matrix.configuration }}\uefiext.dll

      - name: Publish Release Asset
        if: ${{ matrix.configuration == 'Release' && github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Compress-Archive -Path UefiDbgExt\${{ matrix.platform }}\${{ matrix.configuration }}\uefiext.dll -DestinationPath UefiExt_${{ matrix.platform }}.zip
          gh release upload ${{ github.event.release.tag_name }} UefiExt_${{ matrix.platform }}.zip
